version: '3.1'

services:

  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    image: backend
    container_name: backend-container
    stdin_open: true
    tty: true
    